### ISSUE TITLE
UTF8 undefined

### ISSUE THREAD

**Issue by viratshukla** [tensor-programming/flutter_streams#1]
When I am trying to build this project, I am getting following error -
![image](https://user-images.githubusercontent.com/11851800/44517218-b5580900-a6e4-11e8-85bc-753bafcafc15.png)

Please help me to fix it. Currently I am running this project on  intelliJ idea community edition 2018.2. which is latest edition at this time.

**Comment by matiux** [comment]
@tensor-programming I have same issue

**Comment by matiux** [comment]
I have solve in this way:
import 'dart:convert';

and 

transform(utf8.decoder)

**Comment by tensor-programming** [comment]
wow, didn't see this issue.  Yeah, not sure why I was using the depreciated UTF8 over the newer utf8.  I have fixed the source.
